#pragma once
#define STRING_DISTRIBUTION_DATE "2020-08-28"
#define MACHINE_NAME "IMADE3D JellyBOX"
#define SHORT_BUILD_VERSION "jb3.3.1-m2.0.6.1"
#define DETAILED_BUILD_VERSION SHORT_BUILD_VERSION
#define WEBSITE_URL "https://imade3d.com"